- name: Fetch and run Docker image from Docker Hub
  hosts: localhost
  connection: local
  tasks:
    - name: Pull Docker image from Docker Hub
      docker_image:
        name: "gsamrit/calculator:latest"
        source: pull

    - name: Run Docker container
      docker_container:
        name: calculator-container
        image: "gsamrit/calculator:latest"
        state: started
        ports:
          - "8082:8082"